import re
import json
import os

INPUT_FILE = '/Users/eddybouchenak/Documents/GEMINI_APP/MOTSHASARD/SCRIPT_PYTHON/mots_tries.txt'
OUTPUT_FILE = '/Users/eddybouchenak/Documents/GEMINI_APP/MOTSHASARD/js/data.js'

def parse_mots_tries(file_path):
    sorted_words = {}
    current_letter = None
    all_words = []

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        for line in lines:
            line = line.strip()
            if not line:
                continue

            # Check for Letter key like "A":
            letter_match = re.match(r'^"([A-Z])":$', line)
            if letter_match:
                current_letter = letter_match.group(1)
                sorted_words[current_letter] = []
                continue

            # Check for word like "ABRICOT", or "ABRICOT"
            # Some lines might have trailing commas
            word_match = re.match(r'^"([A-Z]+)",?$', line)
            if word_match and current_letter:
                word = word_match.group(1)
                sorted_words[current_letter].append(word)
                all_words.append(word)

        return sorted_words, all_words

    except Exception as e:
        print(f"Error reading file: {e}")
        return None, None

def generate_js_file(sorted_words, all_words, output_path):
    if not sorted_words:
        print("No data to write.")
        return

    js_content = f"""// Generated by transform_data.py
const SORTED_WORDS = {json.dumps(sorted_words, indent=4, ensure_ascii=False)};

const WORDS = {json.dumps(all_words, indent=4, ensure_ascii=False)};

// Expose to global scope
window.SORTED_WORDS = SORTED_WORDS;
window.WORDS = WORDS;
"""

    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(js_content)
        print(f"Successfully generated {output_path}")
        print(f"Total letters: {len(sorted_words)}")
        print(f"Total words: {len(all_words)}")
    except Exception as e:
        print(f"Error writing JS file: {e}")

if __name__ == "__main__":
    print(f"Processing {INPUT_FILE}...")
    sorted_data, flat_data = parse_mots_tries(INPUT_FILE)
    if sorted_data:
        generate_js_file(sorted_data, flat_data, OUTPUT_FILE)
